version: '3'
services:
  story-service:
    build: ./services/story-service
    ports:
      - "3001:3001"
    env_file: ./services/story-service/.env

  tts-service:
    build: ./services/tts-service
    ports:
      - "3002:3002"
    env_file: ./services/tts-service/.env

  image-service:
    build: ./services/image-service
    ports:
      - "3003:3003"
    env_file: ./services/image-service/.env
